Address all IDE0032. Use auto-implemented property.
dotnet/orleans pull request #8614
Opened 2023-08-31 18:51 UTC by IEvangelist

Supersedes part of https://github.com/dotnet/orleans/pull/8471

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/dotnet/orleans/pull/8614)

2023-09-01 14:02 UTC, ReubenBond commented
Are these changes all generated automatically by code fixes? I need to work out what needs closer attention while reviewing and what doesn't. Eg, adding `readonly` to a field often results in the wrong behavior, so that will need special attention.

2023-09-01 16:02 UTC, ReubenBond commented on src/Orleans.Serialization/Session/ReferencedObjectCollection.cs
> -        private uint _currentReferenceId;
We should revert the changes in this file.

2023-09-01 16:02 UTC, ReubenBond commented on src/Orleans.Serialization/Buffers/Adaptors/SpanBufferWriter.cs
> -        private int _bytesWritten;
We should revert the changes in this file.

2023-09-01 16:02 UTC, ReubenBond commented on src/Orleans.Serialization/Buffers/Adaptors/BufferSliceReaderInput.cs
> -    private int _position;
We should revert the changes in this file.

2023-09-01 16:02 UTC, ReubenBond commented on src/Orleans.Core/Messaging/PrefixingBufferWriter.cs
> -        private int _committedBytes;
We should revert the changes in this file.

2023-09-01 16:03 UTC, ReubenBond reviewed
Some reversions needed, otherwise LGTM

2023-09-05 05:56 UTC, pentp requested changes

2023-09-05 05:56 UTC, pentp commented on src/Orleans.Core.Abstractions/IDs/SystemTargetGrainId.cs
> -        private readonly GrainId _grainId;
This should be reverted - it's stored as a field specifically to get better inlining (when accessing it through a property, the subfields cannot be directly addressed by the compiler unless the entire data structure is "inlined").

2023-09-05 05:56 UTC, pentp commented on src/Orleans.Streaming/Common/PooledCache/CachedMessageBlock.cs
> -        private int readIndex;
This should be reverted also for performance & clarity.

2023-09-14 11:52 UTC, IEvangelist commented on src/AdoNet/Shared/Storage/RelationalStorage.cs
> +            using (var connection = DbConnectionFactory.CreateConnection(invariantName, ConnectionString))
```suggestion
            using (var connection = DbConnectionFactory.CreateConnection(_invariantName, ConnectionString))
```

2024-03-26 12:58 UTC, closed without merging